# model information
model_name: "gaussian.Gaussian1d"
model_kwargs:
  N: 128
  V0: -4.0
  R: 2.0

# PMM state information
pmm_name: "PMM"
pmm_kwargs:
  dim: 8
  num_primary: 2
  num_secondary: 0
  eta: 1.0e-2
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  absmaxgrad: 1.0e+3
  l2: 0.0
  mag: 1.0e-1
  seed: 135

# sample data information
try_load: false
k_num_sample: 1
sample_Ls: {"Lmin" : 5.0, "Lmax" : 9.0, "Llen" : 20, "Lexp" : 1.0}

# training information
epochs: 10000
store_loss: 100

# prediction 
k_num_predict: 1
predict_Ls: null 

# plotting information  
plot_kwargs:
  xlabel: "System Length"
  title: "Gaussian1d (V0=-4, R=2)"

# save
save: true
show: true
